export type ErrorCode =
  | "CONFIG_MISMATCH" | "WRITE_API_DISABLED" | "PRICE_NOT_PARTIAL_FILL_SAFE"
  | "INVALID_QUANTITY" | "UINT256_OVERFLOW" | "INVALID_STRUCTURE" | "INVALID_ASSET"
  | "INVALID_SIGNATURE" | "SMART_ACCOUNT_NOT_SUPPORTED" | "INVALID_COUNTER"
  | "INVALID_BALANCE" | "INVALID_APPROVAL" | "ORDER_CANCELLED" | "ORDER_FILLED"
  | "ORDER_EXPIRED" | "VALIDATOR_REJECTED" | "NOT_FOUND" | "RATE_LIMITED"
  | "BATCH_EMPTY" | "BATCH_TOO_MANY_ORDERS" | "BATCH_PLAN_CHANGED"
  | "BATCH_QUOTE_EXPIRED" | "BUDGET_TOO_LOW" | "MAX_PRICE_BELOW_BEST_ASK"
  | "SELF_LISTING" | "LISTING_NOT_FOUND" | "LISTING_NOT_FILLABLE"
  | "LISTING_QUANTITY_CHANGED" | "LISTING_PRICE_CHANGED"
  | "LISTING_CAPACITY_EXCEEDED"
  | "INSUFFICIENT_SELLER_BALANCE" | "INVALID_SELLER_APPROVAL"
  | "INSUFFICIENT_SAFE_BALANCE" | "BATCH_SIMULATION_FAILED" | "BATCH_ACTION_UNEXPECTED"
  | "CIRCUIT_COLLECTION_NOT_ALLOWED" | "CIRCUIT_NOT_FOUND" | "CIRCUIT_NOT_OWNER"
  | "CIRCUIT_ALREADY_LISTED" | "ERC721_APPROVAL_MISSING" | "ERC721_PARTIAL_FILL_FORBIDDEN"
  | "INVALID_ASSET_STANDARD" | "INVALID_ORDER_TYPE" | "INVALID_OWNER" | "INVALID_CURSOR";

export class DomainError extends Error {
  constructor(public readonly code: ErrorCode, message: string, public readonly statusCode = 400, public readonly details?: unknown) {
    super(message);
    this.name = "DomainError";
  }
}
