import { describe, expect, it } from "vitest";
import { Wallet, ZeroAddress, ZeroHash } from "ethers";
import type { PublicClient } from "viem";
import { buildApp } from "../../src/app.js";
import { loadConfig } from "../../src/config.js";
import type { ListingRecord } from "../../src/domain/listing.js";
import { RESERVING_LISTING_STATUSES } from "../../src/domain/listing.js";
import { assertListingCapacity, calculateListingCapacity } from "../../src/domain/listing-capacity.js";
import { decodeMarketCursor, encodeMarketCursor, type InsertWithCapacityCheckInput, type ListingCapacityKey, type ListingQuery, type ListingRepository, type ListingValidationPatch, type MarketIdentity, type MarketPageQuery, type SweepCandidateQuery } from "../../src/db/repository.js";
import { ORDER_TYPES } from "../../src/domain/signature.js";

const processor = "0x4444444444444444444444444444444444444444"; const token = "0x2222222222222222222222222222222222222222"; const fee = "0x3333333333333333333333333333333333333333";
class MemoryTestRepository implements ListingRepository {
  private capacityQueue: Promise<void> = Promise.resolve();
  rows = new Map<string, ListingRecord>(); async ready() { return true; } async get(hash: string) { return this.rows.get(hash.toLowerCase()) ?? null; }
  async getMany(hashes: string[]) { return hashes.flatMap((hash) => { const row = this.rows.get(hash.toLowerCase()); return row ? [row] : []; }); }
  async insert(row: ListingRecord) { this.rows.set(row.orderHash.toLowerCase(), row); return row; }
  async getReservedListingQuantity(input: ListingCapacityKey) { const now = BigInt(input.nowSeconds ?? String(Math.floor(Date.now() / 1_000))); return [...this.rows.values()].filter((row) => row.offerer.toLowerCase() === input.offerer.toLowerCase() && row.transistorsAddress.toLowerCase() === input.transistorsAddress.toLowerCase() && row.tokenId === input.tokenId && BigInt(row.endTime) > now && RESERVING_LISTING_STATUSES.includes(row.status as typeof RESERVING_LISTING_STATUSES[number])).reduce((sum, row) => sum + BigInt(row.remainingQuantity), 0n).toString(); }
  async getListingCapacity(input: ListingCapacityKey & { walletBalance: string }) { const reserved = await this.getReservedListingQuantity(input); const count = [...this.rows.values()].filter((row) => row.offerer.toLowerCase() === input.offerer.toLowerCase() && row.transistorsAddress.toLowerCase() === input.transistorsAddress.toLowerCase() && row.tokenId === input.tokenId && BigInt(row.endTime) > BigInt(input.nowSeconds ?? String(Math.floor(Date.now() / 1_000))) && RESERVING_LISTING_STATUSES.includes(row.status as typeof RESERVING_LISTING_STATUSES[number])).length; return calculateListingCapacity(input.walletBalance, reserved, count); }
  async insertWithCapacityCheck({ listing, walletBalance, nowSeconds }: InsertWithCapacityCheckInput) { let release!: () => void; const previous = this.capacityQueue; this.capacityQueue = new Promise<void>((resolve) => { release = resolve; }); await previous; try { const existing = await this.get(listing.orderHash); if (existing) return existing; const capacity = await this.getListingCapacity({ offerer: listing.offerer, transistorsAddress: listing.transistorsAddress, tokenId: listing.tokenId, walletBalance, ...(nowSeconds ? { nowSeconds } : {}) }); assertListingCapacity(capacity, listing.initialQuantity, listing.assetType); return this.insert(listing); } finally { release(); } }
  async list(q: ListingQuery) { return [...this.rows.values()].filter((r) => (!q.transistorsAddress || r.transistorsAddress.toLowerCase() === q.transistorsAddress.toLowerCase()) && (!q.tokenId || r.tokenId === q.tokenId) && (!q.offerer || r.offerer.toLowerCase() === q.offerer.toLowerCase()) && (!q.statuses || q.statuses.includes(r.status))).sort((a, b) => BigInt(a.sellerUnitPriceWei) === BigInt(b.sellerUnitPriceWei) ? a.orderHash.localeCompare(b.orderHash) : BigInt(a.sellerUnitPriceWei) < BigInt(b.sellerUnitPriceWei) ? -1 : 1).slice(0, q.limit ?? 50); }
  async listMarketPage(q: MarketPageQuery) { const cursor = q.cursor ? decodeMarketCursor(q.cursor) : null; const all = (await this.list({ ...q, limit: 10_000 })).filter((row) => !cursor || BigInt(row.sellerUnitPriceWei) > BigInt(cursor.sellerUnitPriceWei) || (row.sellerUnitPriceWei === cursor.sellerUnitPriceWei && row.orderHash.toLowerCase() > cursor.orderHash)); const listings = all.slice(0, q.limit); const last = listings.at(-1); return { listings, nextCursor: all.length > q.limit && last ? encodeMarketCursor({ sellerUnitPriceWei: last.sellerUnitPriceWei, orderHash: last.orderHash }) : null }; }
  async listSweepCandidates(q: SweepCandidateQuery) { return (await this.list({ transistorsAddress: q.transistorsAddress, tokenId: q.tokenId, statuses: q.statuses, limit: q.limit })).filter((row) => row.offerer.toLowerCase() !== q.excludeOfferer.toLowerCase() && BigInt(row.sellerUnitPriceWei) <= BigInt(q.maxSellerUnitPriceWei)); }
  async updateValidation(hash: string, patch: Partial<ListingRecord>) { const row = await this.get(hash); if (!row) return null; const next = { ...row, ...patch }; this.rows.set(hash.toLowerCase(), next); return next; } async close() {}
  async revalidateMany(updates: Array<{ orderHash: string; patch: ListingValidationPatch }>) { return (await Promise.all(updates.map(({ orderHash, patch }) => this.updateValidation(orderHash, patch)))).filter((row): row is ListingRecord => row !== null); }
  async listFills() { return []; }
  async summaries(markets: MarketIdentity[]) { return { summaries: await Promise.all(markets.map(async ({ transistorsAddress, tokenId }) => { const rows = await this.list({ transistorsAddress, tokenId, statuses: ["ACTIVE", "PARTIALLY_FILLED"] }); return { transistorsAddress, tokenId, bestAskWei: rows[0]?.sellerUnitPriceWei ?? null, bestAskBuyerTotalWei: rows[0]?.buyerUnitTotalWei ?? null, activeListingCount: String(rows.length), activeListingQuantity: rows.reduce((sum, row) => sum + BigInt(row.remainingQuantity), 0n).toString(), lastSeaportSaleWei: null, lastSeaportSaleAt: null, lastSeaportSaleTxHash: null, seaportVolume24hWei: "0", seaportVolumeAllTimeWei: "0", seaportFillCount24h: "0" }; })), generatedAt: new Date().toISOString(), lastIndexedBlock: "123", indexerStale: false }; }
  async summary(transistorsAddress: string, tokenId: string) { return (await this.summaries([{ transistorsAddress, tokenId }])).summaries[0]!; }
}
function fakeClient(wallet: string): PublicClient {
  return { getBlockNumber: async () => 123n, getCode: async ({ address }: any) => address.toLowerCase() === wallet.toLowerCase() ? "0x" : "0x6000", readContract: async ({ functionName }: any) => {
    if (functionName === "isCPU" || functionName === "supportsInterface" || functionName === "isApprovedForAll") return true;
    if (functionName === "transistors") return token; if (functionName === "circuits") return processor; if (functionName === "balanceOf") return 100n;
    if (functionName === "getCounter") return 0n; if (functionName === "getOrderStatus") return [false, false, 0n, 0n];
    if (functionName === "isValidOrderWithConfiguration") return { errors: [], warnings: [] }; throw new Error(`Unexpected ${functionName}`);
  } } as unknown as PublicClient;
}
describe("API v1 listing lifecycle", () => {
  it("quotes, validates, stores idempotently, queries and revalidates", async () => {
    const wallet = Wallet.createRandom(); const now = Math.floor(Date.now() / 1000); const config = loadConfig({ NODE_ENV: "test", DATABASE_URL: "postgresql://unused", BSC_RPC_HTTP_URL: "http://localhost:8545", FEE_RECIPIENT: fee, CHAIN_STARTUP_CHECK: "false" }); const repository = new MemoryTestRepository(); const app = await buildApp({ config, repository, chainClient: fakeClient(wallet.address) });
    const quote = await app.inject({ method: "POST", url: "/api/v1/listings/quote", payload: { processorAddress: processor, transistorsAddress: token, tokenId: "0", sellerUnitPriceWei: "10000", quantity: "10", endTime: String(now + 604800) } }); expect(quote.statusCode).toBe(200); expect(quote.json().buyerTotalWei).toBe("101000");
    const parameters = { offerer: wallet.address, zone: ZeroAddress, offer: [{ itemType: 3, token, identifierOrCriteria: "0", startAmount: "10", endAmount: "10" }], consideration: [{ itemType: 0, token: ZeroAddress, identifierOrCriteria: "0", startAmount: "100000", endAmount: "100000", recipient: wallet.address }, { itemType: 0, token: ZeroAddress, identifierOrCriteria: "0", startAmount: "1000", endAmount: "1000", recipient: fee }], orderType: 1, startTime: String(now - 10), endTime: String(now + 604800), zoneHash: ZeroHash, salt: "1", conduitKey: ZeroHash, totalOriginalConsiderationItems: 2, counter: "0" };
    const signature = await wallet.signTypedData({ name: "Seaport", version: "1.6", chainId: 56, verifyingContract: config.seaportAddress }, ORDER_TYPES, parameters); const payload = { processorAddress: processor, parameters, signature };
    const created = await app.inject({ method: "POST", url: "/api/v1/listings", payload }); expect(created.statusCode).toBe(201); const listing = created.json(); expect(listing.status).toBe("ACTIVE"); expect(listing.parameters.totalOriginalConsiderationItems).toBe("2"); expect(listing.validatorCodes.errors).toEqual([]);
    const duplicate = await app.inject({ method: "POST", url: "/api/v1/listings", payload: { ...payload, orderHash: listing.orderHash } }); expect(duplicate.statusCode).toBe(200); expect(repository.rows.size).toBe(1);
    const secondParameters = { ...parameters, salt: "2" }; const secondSignature = await wallet.signTypedData({ name: "Seaport", version: "1.6", chainId: 56, verifyingContract: config.seaportAddress }, ORDER_TYPES, secondParameters); const second = (await app.inject({ method: "POST", url: "/api/v1/listings", payload: { processorAddress: processor, parameters: secondParameters, signature: secondSignature } })).json();
    const firstPage = (await app.inject({ method: "GET", url: `/api/v1/markets/${token}/0/listings?limit=1` })).json(); expect(firstPage.listings).toHaveLength(1); expect(firstPage.nextCursor).toEqual(expect.any(String));
    const secondPage = (await app.inject({ method: "GET", url: `/api/v1/markets/${token}/0/listings?limit=1&cursor=${encodeURIComponent(firstPage.nextCursor)}` })).json(); expect(secondPage.listings).toHaveLength(1); expect(secondPage.listings[0].orderHash).not.toBe(firstPage.listings[0].orderHash);
    expect((await app.inject({ method: "GET", url: `/api/v1/accounts/${wallet.address}/listings` })).json().listings).toHaveLength(2);
    const buyer = Wallet.createRandom().address;
    const selected = await app.inject({ method: "POST", url: `/api/v1/markets/${token}/0/batch-quote`, payload: { mode: "SELECTED", buyer, items: [{ orderHash: listing.orderHash, quantity: "2" }] } }); expect(selected.statusCode).toBe(200); expect(selected.json()).toMatchObject({ mode: "SELECTED", orderCount: 1, totalUnits: "2", disclaimer: "This quote does not reserve listings." });
    const sweep = await app.inject({ method: "POST", url: `/api/v1/markets/${token}/0/batch-quote`, payload: { mode: "SWEEP", buyer, budgetWei: "202000", maxSellerUnitPriceWei: "10000", maxOrders: 2 } }); expect(sweep.statusCode).toBe(200); expect(sweep.json()).toMatchObject({ mode: "SWEEP", orderCount: 2, totalUnits: "20" });
    const changed = await app.inject({ method: "POST", url: `/api/v1/markets/${token}/0/batch-quote`, payload: { mode: "SELECTED", buyer, items: [{ orderHash: listing.orderHash, quantity: "2" }], expectedPlanHash: ZeroHash } }); expect(changed.statusCode).toBe(409); expect(changed.json().error.code).toBe("BATCH_PLAN_CHANGED");
    const expired = await app.inject({ method: "POST", url: `/api/v1/markets/${token}/0/batch-quote`, payload: { mode: "SELECTED", buyer, items: [{ orderHash: listing.orderHash, quantity: "2" }], expectedPlanHash: selected.json().planHash, quoteExpiresAt: "2000-01-01T00:00:00.000Z" } }); expect(expired.statusCode).toBe(409); expect(expired.json().error.code).toBe("BATCH_QUOTE_EXPIRED");
    const own = await app.inject({ method: "POST", url: `/api/v1/markets/${token}/0/batch-quote`, payload: { mode: "SELECTED", buyer: wallet.address, items: [{ orderHash: listing.orderHash, quantity: "1" }] } }); expect(own.statusCode).toBe(409); expect(own.json().error.code).toBe("BATCH_PLAN_CHANGED");
    const wrongMarket = await app.inject({ method: "POST", url: "/api/v1/markets/0x7777777777777777777777777777777777777777/0/batch-quote", payload: { mode: "SELECTED", buyer, items: [{ orderHash: listing.orderHash, quantity: "1" }] } }); expect(wrongMarket.statusCode).toBe(409); expect(wrongMarket.json().error.code).toBe("BATCH_PLAN_CHANGED");
    const wrongToken = await app.inject({ method: "POST", url: `/api/v1/markets/${token}/2/batch-quote`, payload: { mode: "SWEEP", buyer, budgetWei: "10100", maxSellerUnitPriceWei: "10000", maxOrders: 1 } }); expect(wrongToken.statusCode).toBe(400); expect(wrongToken.json().error.code).toBe("INVALID_REQUEST");
    const revalidated = await app.inject({ method: "POST", url: "/api/v1/listings/revalidate-batch", payload: { orderHashes: [listing.orderHash, second.orderHash, listing.orderHash] } }); expect(revalidated.statusCode).toBe(200); expect(revalidated.json().results).toHaveLength(2);
    const publicConfig = (await app.inject({ method: "GET", url: "/api/v1/config" })).json(); expect(publicConfig).toMatchObject({ batchQuoteTtlSeconds: 15, maxBatchOrders: 20, batchEnabled: true });
    expect((await app.inject({ method: "POST", url: `/api/v1/listings/${listing.orderHash}/revalidate` })).json().status).toBe("ACTIVE");
    const limited = await Promise.all(Array.from({ length: 21 }, () => app.inject({ method: "POST", url: `/api/v1/markets/${token}/0/batch-quote`, payload: { mode: "SWEEP", buyer, budgetWei: "10100", maxSellerUnitPriceWei: "10000", maxOrders: 1 } })));
    expect(limited.some((response) => response.statusCode === 429)).toBe(true); await app.close();
  });
  it("keeps writes disabled without a fee recipient", async () => { const config = loadConfig({ NODE_ENV: "test", DATABASE_URL: "postgresql://unused", BSC_RPC_HTTP_URL: "http://localhost:8545", CHAIN_STARTUP_CHECK: "false" }); const app = await buildApp({ config, repository: new MemoryTestRepository(), chainClient: fakeClient(ZeroAddress) }); expect((await app.inject({ method: "POST", url: "/api/v1/listings/quote", payload: {} })).statusCode).toBe(503); await app.close(); });
  it("reports capacity, rejects quote and submission overcommit, stays idempotent and serializes concurrent submissions", async () => {
    const wallet = Wallet.createRandom(); const config = loadConfig({ NODE_ENV: "test", DATABASE_URL: "postgresql://unused", BSC_RPC_HTTP_URL: "http://localhost:8545", FEE_RECIPIENT: fee, CHAIN_STARTUP_CHECK: "false" }); const repository = new MemoryTestRepository(); const app = await buildApp({ config, repository, chainClient: fakeClient(wallet.address) });
    const now = Math.floor(Date.now() / 1_000);
    const payloadFor = async (quantity: string, salt: string) => {
      const sellerTotal = (BigInt(quantity) * 10_000n).toString(); const feeTotal = (BigInt(quantity) * 100n).toString();
      const parameters = { offerer: wallet.address, zone: ZeroAddress, offer: [{ itemType: 3, token, identifierOrCriteria: "0", startAmount: quantity, endAmount: quantity }], consideration: [{ itemType: 0, token: ZeroAddress, identifierOrCriteria: "0", startAmount: sellerTotal, endAmount: sellerTotal, recipient: wallet.address }, { itemType: 0, token: ZeroAddress, identifierOrCriteria: "0", startAmount: feeTotal, endAmount: feeTotal, recipient: fee }], orderType: 1, startTime: String(now - 10), endTime: String(now + 604_800), zoneHash: ZeroHash, salt, conduitKey: ZeroHash, totalOriginalConsiderationItems: 2, counter: "0" };
      const signature = await wallet.signTypedData({ name: "Seaport", version: "1.6", chainId: 56, verifyingContract: config.seaportAddress }, ORDER_TYPES, parameters);
      return { processorAddress: processor, parameters, signature };
    };
    const capacityUrl = `/api/v1/accounts/${wallet.address}/markets/${token}/0/listing-capacity`;
    expect((await app.inject({ method: "GET", url: capacityUrl })).json()).toMatchObject({ walletBalance: "100", reservedListingQuantity: "0", availableToList: "100", overcommittedQuantity: "0", reservingListingCount: 0, assetType: "NAND", asOfBlock: "123" });
    const quoteRejected = await app.inject({ method: "POST", url: "/api/v1/listings/quote", payload: { processorAddress: processor, transistorsAddress: token, tokenId: "0", sellerUnitPriceWei: "10000", quantity: "101", endTime: String(now + 604_800), offerer: wallet.address } });
    expect(quoteRejected.statusCode).toBe(409); expect(quoteRejected.json().error).toMatchObject({ code: "LISTING_CAPACITY_EXCEEDED", details: { availableToList: "100", requestedQuantity: "101" }, requestId: expect.any(String) });
    const firstPayload = await payloadFor("60", "1001"); const first = await app.inject({ method: "POST", url: "/api/v1/listings", payload: firstPayload }); expect(first.statusCode).toBe(201);
    expect((await app.inject({ method: "GET", url: capacityUrl })).json()).toMatchObject({ reservedListingQuantity: "60", availableToList: "40", reservingListingCount: 1 });
    const over = await app.inject({ method: "POST", url: "/api/v1/listings", payload: await payloadFor("50", "1002") }); expect(over.statusCode).toBe(409); expect(over.json().error.code).toBe("LISTING_CAPACITY_EXCEEDED");
    const duplicate = await app.inject({ method: "POST", url: "/api/v1/listings", payload: { ...firstPayload, orderHash: first.json().orderHash } }); expect(duplicate.statusCode).toBe(200); expect(repository.rows.size).toBe(1);
    await repository.updateValidation(first.json().orderHash, { status: "CANCELLED" }); expect((await app.inject({ method: "GET", url: capacityUrl })).json().availableToList).toBe("100");
    const concurrent = await Promise.all([app.inject({ method: "POST", url: "/api/v1/listings", payload: await payloadFor("60", "1003") }), app.inject({ method: "POST", url: "/api/v1/listings", payload: await payloadFor("60", "1004") })]);
    expect(concurrent.map((response) => response.statusCode).sort()).toEqual([201, 409]);
    const summaries = await app.inject({ method: "POST", url: "/api/v1/markets/summaries", payload: { markets: [{ transistorsAddress: token, tokenId: "0" }, { transistorsAddress: token, tokenId: "0" }] } });
    expect(summaries.statusCode).toBe(200); expect(summaries.json()).toMatchObject({ summaries: [{ transistorsAddress: token, tokenId: "0", seaportVolume24hWei: "0" }], lastIndexedBlock: "123", indexerStale: false });
    await app.close();
  });
});
